{
 "title": "gRPC Server Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total - 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(name_lengths_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rate - 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(name_lengths_bucket[1m])", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Total - 1m",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(name_lengths_bucket[1m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "name_lengths_count" }
   ]
  },
  {
   "title": "rate(sum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(name_lengths_sum[1m])" }
   ]
  }
 ]
}